DROP TABLE IF EXISTS resource_ratings CASCADE;

CREATE TABLE resource_ratings (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  resource_id INTEGER REFERENCES resources(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL DEFAULT 0,
  like BOOLEAN NOT NULL DEFAULT FALSE
);
